import Link from "next/link";
import { AcademicCapIcon } from "@heroicons/react/24/outline";

export const metadata = {
  title: "Terms of Service — QuizForge",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Nav */}
      <nav className="bg-white border-b border-slate-200">
        <div className="max-w-6xl mx-auto px-4 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center">
              <AcademicCapIcon className="w-5 h-5 text-white" />
            </div>
            <span className="font-bold text-lg text-slate-900">QuizForge</span>
          </Link>
        </div>
      </nav>

      <main className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: January 1, 2025</p>

        <div className="space-y-8 text-slate-700">
          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">1. Acceptance of Terms</h2>
            <p className="text-sm leading-relaxed">
              By creating an account or using QuizForge, you agree to these Terms of Service. If you do not agree, please do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">2. Permitted Use</h2>
            <p className="text-sm leading-relaxed mb-3">
              QuizForge is designed for educators to create educational assessments. You agree to use QuizForge only for lawful educational purposes. You may not:
            </p>
            <ul className="text-sm leading-relaxed space-y-2 list-disc pl-5">
              <li>Attempt to circumvent usage limits through automated means</li>
              <li>Share your account credentials with others</li>
              <li>Use the service to generate harmful, illegal, or inappropriate content</li>
              <li>Reverse engineer or attempt to extract our underlying systems</li>
              <li>Use the service in a way that violates applicable laws</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">3. Free and Pro Plans</h2>
            <p className="text-sm leading-relaxed mb-3">
              <strong>Free Plan:</strong> Free accounts receive 3 quiz generations per day. We reserve the right to adjust free limits with notice.
            </p>
            <p className="text-sm leading-relaxed">
              <strong>Pro Plan:</strong> Pro subscriptions are billed monthly. You can cancel at any time. Upon cancellation, you retain Pro access until the end of the current billing period, then revert to the Free plan.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">4. Payment and Refunds</h2>
            <p className="text-sm leading-relaxed mb-3">
              Pro subscriptions are billed monthly via Stripe. We do not store payment card information.
              Refunds are issued on a case-by-case basis — contact us within 7 days of a charge if you believe you were billed in error.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">5. Content Ownership</h2>
            <p className="text-sm leading-relaxed">
              You own the quiz topics and inputs you provide. The generated quiz content is provided to you for educational use.
              QuizForge retains no ownership claim over quizzes you generate. However, we may use anonymized usage data to improve the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">6. AI-Generated Content</h2>
            <p className="text-sm leading-relaxed">
              Quiz content is generated by Claude AI (Anthropic). While we strive for accuracy, AI-generated content may contain errors.
              You are responsible for reviewing generated quizzes before distributing them to students. QuizForge is a tool, not a replacement for teacher judgment.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">7. Availability and Changes</h2>
            <p className="text-sm leading-relaxed">
              We strive for high availability but do not guarantee uninterrupted service. We may update features, pricing, or these terms with reasonable notice.
              Continued use after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">8. Termination</h2>
            <p className="text-sm leading-relaxed">
              You may delete your account at any time from your profile settings. We may suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">9. Limitation of Liability</h2>
            <p className="text-sm leading-relaxed">
              QuizForge is provided &ldquo;as is&rdquo; without warranty of any kind. To the maximum extent permitted by law, QuizForge shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-slate-900 mb-3">10. Contact</h2>
            <p className="text-sm leading-relaxed">
              Questions about these terms?{" "}
              <Link href="/contact" className="text-indigo-600 hover:underline">
                Contact us
              </Link>
              .
            </p>
          </section>
        </div>
      </main>

      <footer className="bg-slate-900 text-slate-400 py-6 px-4 text-sm mt-12">
        <div className="max-w-6xl mx-auto flex justify-between items-center">
          <span>© {new Date().getFullYear()} QuizForge</span>
          <div className="flex gap-4">
            <Link href="/privacy" className="hover:text-slate-200">Privacy</Link>
            <Link href="/terms" className="hover:text-slate-200">Terms</Link>
            <Link href="/contact" className="hover:text-slate-200">Contact</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
