"""add_soft_delete_and_print_time_to_generations

Revision ID: 89c26b693882
Revises: 8929d581e6d3
Create Date: 2026-02-22 11:45:18.485971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c26b693882'
down_revision: Union[str, None] = '8929d581e6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generations', sa.Column('estimated_print_time', sa.String(), nullable=True))
    op.add_column('generations', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generations', 'is_deleted')
    op.drop_column('generations', 'estimated_print_time')
    # ### end Alembic commands ###
